feed_crawler/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

server/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from server import views


urlpatterns = [
    url(r'^', include('feed_crawler.urls', namespace='feed_crawler')),
    url(r'^accounts/login/$', auth_views.LoginView.as_view(
        template_name='login.html', redirect_authenticated_user=True),
        name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),
    url(r'^logout/$', views.logout_user, name='logout'),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

feed_crawler/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

feed_crawler/views.py
# -*- coding: utf-8 -*-

import json
import os

from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render
from django.http import HttpResponse
from django.conf import settings

from wsgiref.util import FileWrapper
from core.lib import XMLTool

base_dir = settings.BASE_DIR


@csrf_exempt
@login_required()
def index(request):

    if request.method == 'GET':
        return render(request, 'base.html')

    if request.method == 'POST':

        # Defining XML source
        URL = "http://revistaautoesporte.globo.com/rss/ultimas/feed.xml"

        # Creating XMLTool object (passing the URL)
        xml_obj = XMLTool(xml_url=URL)

        # Converting XML to JSON and saving in a .json file
        json_obj = xml_obj.xml_to_json()

        json_obj = json.dumps(json_obj, sort_keys=True,
                              indent=3, separators=(',', ': '),
                              ensure_ascii=False).encode('utf8')

        with open(base_dir + '/feed_crawler/tmp/feed.json', "w+") as json_file:
            json_file.write(json_obj)

        return send_file(base_dir + '/feed_crawler/tmp/feed.json', "feed.json")


def send_file(filename, download_name):

    wrapper = FileWrapper(open(filename))
    response = HttpResponse(wrapper, content_type='application/force-download')
    response['Content-Length'] = os.path.getsize(filename)
    response['Content-Disposition'] = "attachment; filename=%s" % download_name

    return response

server/views.py
# -*- coding: utf-8 -*-

#
# Copyright (C) 2013-2017,
# TGR - Tecnologia em Gestão de Redes S.A.
#

from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import redirect


@login_required()
def logout_user(request):
    logout(request)
    return HttpResponseRedirect('../')

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link rel="icon" href="../../favicon.ico">
    <title>Desafio Infoglobo</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Desafio Infoglobo</a>
        </div>
        {% if user.is_authenticated %}
        <form class="navbar-form navbar-right" action="{% url 'logout' %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-primary">
            <span class="fa fa-sign-out"></span>
            Logout
          </button>
        </form>
        {% endif %}
      </div>
    </nav>
    <div class="container">
      <div class="page-header">
        <br>
        <h1>Feed Crawler</h1>
      </div>
      <p class="lead">Esse crawler converte o feed de notícias da revista auto esporte de XML para JSON.</p>
      <div class="row">
        <div class="col-lg-8">
          <div class="input-group">
            <input type="text" class="form-control" value="http://revistaautoesporte.globo.com/rss/ultimas/feed.xml">
            <span class="input-group-btn">
              <button id="convert_button" class="btn btn-default" type="button">Converter</button>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <form>
        <div class="form-group">
          <br>
          <label for="comment">JSON Output:</label>
          <textarea id="json_feed" class="form-control" rows="15" style="overflow:auto;resize:none"></textarea>
        </div>
      </form>
    </div>
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/loading.js"></script>
    <script type="text/javascript">
      $(function() {
          $( "#convert_button" ).click(function() {
            setTimeout(function () {
              $.ajax({
                  type:"POST",
                  url:"{% url 'feed_crawler:index' %}",
                  success: function(data, textStatus) {
                      if (data) {
                        waitingDialog.hide();
                        $('#json_feed').val(data);
                      }
                  }
              })
              waitingDialog.show('Convertendo...', {dialogSize: 'sm'});
            }, 10000);
          })
        });
      </script>
  </body>
</html>

templates/login.html
<html>
<head>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/signin.css" rel="stylesheet">
    <title>Login</title>
</head>
<body>
    <div class="container">
        {% block content %}
        <form class="form-signin" method="post" action=".">
            {% csrf_token %}
            <h2 class="form-signin-heading">Desafio Infoglobo</h2>
            <div class="form-group">
                <label for="id_username" style="margin:0px 5px 5px 0px;">Usuário</label>
                {{ form.username }}
            </div>
            <div class="form-group">
                <label for="id_password" style="margin:0px 5px 5px 0px;">Senha</label>
                {{ form.password }}
            </div>
            <input type="submit" class="btn btn-lg btn-primary" value="Entrar"/>

            {% if form.errors %}
            <p>
                <div class="alert alert-danger">
                    <strong>Erro!</strong> Usuário ou senha incorretos. Tente novamente.
                </div>
            </p>
            {% endif %}
        </form>
        {% endblock %}
    </div>
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
</body>
</html>